### ISSUE TITLE
I get this error: "Caused by: java.io.IOException: failed to delete file: /mnt/sdcard/Android/data/mypackage/cache/media/361bd6dab3696905ef0139a9e9969820a98218 83b4b8d0d014bdf3f7f313eede.0"

### ISSUE THREAD

**Issue by cutler** [JakeWharton/DiskLruCache#49]
details:
        at com.jakewharton.disklrucache.Util.deleteContents(Util.java:62)
        at com.jakewharton.disklrucache.DiskLruCache.delete(DiskLruCache.java:654)
        at com.jakewharton.disklrucache.DiskLruCache.open(DiskLruCache.java:236)

```
    android_ver = 2.3.5, avail_mem = 50.109375M, display = 480x320, start at 2013-11-13T06:30:55.000+08:00, crash at 2013-11-13T07:08:08.000+08:00
```

**Comment by newfivefour** [comment]
I have this same issue. 

I do speak English, however:

E/AndroidRuntime( 8674): java.lang.RuntimeException: java.io.IOException: failed to delete /data/data/com.example.app/cache/6
2770830e31053f34aee2c1a136a1cf3.1
E/AndroidRuntime( 8674):        at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
E/AndroidRuntime( 8674):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 8674):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 8674):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 8674): Caused by: java.io.IOException: failed to delete /data/data/com.example.app/cache/62770830e31053f34aee2c1a136a1cf3.1
E/AndroidRuntime( 8674):        at com.squareup.okhttp.internal.DiskLruCache.deleteIfExists(DiskLruCache.java:394)
E/AndroidRuntime( 8674):        at com.squareup.okhttp.internal.DiskLruCache.removeEntry(DiskLruCache.java:585)
E/AndroidRuntime( 8674):        at com.squareup.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:638)
E/AndroidRuntime( 8674):        at com.squareup.okhttp.internal.DiskLruCache.access$100(DiskLruCache.java:88)
E/AndroidRuntime( 8674):        at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:169)
E/AndroidRuntime( 8674):        ... 3 more

Since it's error'ing in the library, not in my app, I cannot try/catch to stop the crash.

**Comment by 3c133ps3d** [comment]
Any workaround?
Error is still present after several years.

**Comment by 3c133ps3d** [comment]
> Caused by java.io.IOException: failed to delete /mnt/expand/865ccc00-bcc9-462a-8c57-2bba375fe503/user/0/com.expertoption/cache/e58254731086bffc6a6af17aef586e6e.1

       at com.squareup.okhttp.internal.io.FileSystem$1.delete + 70(FileSystem.java:70)
       at com.squareup.okhttp.internal.DiskLruCache.removeEntry + 607(DiskLruCache.java:607)
       at com.squareup.okhttp.internal.DiskLruCache.trimToSize + 664(DiskLruCache.java:664)
       at com.squareup.okhttp.internal.DiskLruCache.access$200 + 88(DiskLruCache.java:88)
       at com.squareup.okhttp.internal.DiskLruCache$1.run + 175(DiskLruCache.java:175)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1133(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 607(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run + 761(Thread.java:761)

**Comment by 3c133ps3d** [comment]
> Caused by java.io.IOException: failed to delete /mnt/expand/865ccc00-bcc9-462a-8c57-2bba375fe503/user/0/mypackage/cache/e58254731086bffc6a6af17aef586e6e.1

       at com.squareup.okhttp.internal.io.FileSystem$1.delete + 70(FileSystem.java:70)
       at com.squareup.okhttp.internal.DiskLruCache.removeEntry + 607(DiskLruCache.java:607)
       at com.squareup.okhttp.internal.DiskLruCache.trimToSize + 664(DiskLruCache.java:664)
       at com.squareup.okhttp.internal.DiskLruCache.access$200 + 88(DiskLruCache.java:88)
       at com.squareup.okhttp.internal.DiskLruCache$1.run + 175(DiskLruCache.java:175)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1133(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 607(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run + 761(Thread.java:761)

**Comment by vijaydhas** [comment]
Adding logs just incase there is plan to fix this

Fatal Exception: java.lang.RuntimeException: java.io.IOException: failed to delete /data/user/0/package/cache/picasso-cache/5c9c1b3f5eac43c0eeee56965f918676.1
       at com.android.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:181)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Comment by prabal-18** [comment]
getting it in a spark job, any workaround?

py4j.protocol.Py4JJavaError: An error occurred while calling o2070.save.
java.io.IOException: Failed to delete key: temp/jd_etl/jd_models_staging_data
at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem.delete(S3NativeFileSystem.java:345)
at com.amazon.ws.emr.hadoop.fs.EmrFileSystem.delete(EmrFileSystem.java:418)
at org.apache.spark.internal.io.FileCommitProtocol.deleteWithJob(FileCommitProtocol.scala:124)
