### ISSUE TITLE
A resource was acquired at attached stack trace but never released.

### ISSUE THREAD

**Issue by caxton** [JakeWharton/DiskLruCache#72]
This version still have leakage issue:

09-09 21:47:38.549 31155 31164 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
09-09 21:47:38.549 31155 31164 E StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
09-09 21:47:38.549 31155 31164 E StrictMode:    at dalvik.system.CloseGuard.open(CloseGuard.java:184)
09-09 21:47:38.549 31155 31164 E StrictMode:    at java.io.FileInputStream.<init>(FileInputStream.java:80)
09-09 21:47:38.549 31155 31164 E StrictMode:    at com.htc.lib2.photoplatformcachemanager.DiskLruCache.get(DiskLruCache.java:423)
...

**Comment by necronet** [comment]
I think this is duplicated on https://github.com/square/picasso/issues/296
